development: &default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  <% if ENV['POSTGRES_PASSWORD'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  <% end %>
  adapter: <%= ENV['DB_ADAPTER'] %>
  encoding: utf8
  pool: 5

test:
  <<: *default
  database: slowmonster_test

production:
  <<: *default
  database: slowmonster_production
